name: Bromine
author: srnyx
description: General essentials for Venox Network

main: network.venox.bromine.Main
version: ${version}
api-version: 1.18

load: STARTUP
softdepend:
  - Multiverse-Core

commands:
  chattitle:
    description: "Sends a player's chat as sub-title"
    usage: "Usage: /<command> [player]"
    permission: bromine.chattitle
  brreload:
    description: "Reloads the plugin files"
    usage: "Usage: /<command>"
    permission: bromine.reload
  reset:
    description: "Resets the world(s)"
    usage: "Usage: /<command>"
    permission: bromine.reset

permissions:
  bromine.chattitle:
    description: "Gives access to /chattitle"
  bromine.reload:
    description: "Gives access to /brreload"
  bromine.reset:
    description: "Gives access to /reset"