name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    with:
      modrinth: SMLaeLe2
      curseforge: 895687
    secrets: inherit
